### ISSUE TITLE
Support older NeoVim builds

### ISSUE THREAD

**Issue by kkoomen** [thinca/action-setup-vim#2]
### Describe the bug
I'd like to build for neovim v0.2.0 but when forcing to build from source it fails. I've used a custom docker before based on [Vimjas/vim-testbed](https://github.com/Vimjas/vim-testbed) and this repo is able to build successfully for v0.2.0.

### How to reproduce the problem
```yaml
strategy:
  matrix:
    vim_type: ['neovim']
    os: ['ubuntu-latest', 'macos-latest']
    include:
        vim_version: 'v0.2.0'
runs-on: '${{ matrix.os }}'
steps:
  - uses: 'actions/checkout@v2'
  - name: 'Setup Vim'
    id: 'vim'
    uses: 'thinca/action-setup-vim@v1'
    with:
      vim_version: '${{ matrix.vim_version }}'
      vim_type: neovim
  - name: 'Run test'
    run: |
      # Show Vim's version
      ${{ steps.vim.outputs.executable }} --version
      # ... run tests ...
```

### Expected behavior

It should build successfully for v0.2.0

### Actual behavior

It fails with an error at the `make` command.
